packages:
    - website

overrides:
    copy-webpack-plugin>serialize-javascript: ^7.0.4
    css-minimizer-webpack-plugin>serialize-javascript: ^7.0.4

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
    - '@apify/*'
    - '@crawlee/*'
    - 'apify-client'
    - 'apify'
    - 'crawlee'
    - 'got-scraping'

onlyBuiltDependencies:
    - '@playwright/browser-chromium'
    - '@swc/core'
    - esbuild
    - playwright
    - puppeteer

nodeLinker: hoisted
linkWorkspacePackages: true
preferWorkspacePackages: true
publicHoistPattern:
    - '*'
