packages:
  - website

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@apify/*'
  - '@crawlee/*'
  - 'apify-client'
  - 'apify'
  - 'crawlee'
  - 'got-scraping'
  # Renovate security update: vitest@4.1.0
  - vitest@4.1.0

allowBuilds:
  '@apify/ui-icons': false
  '@playwright/browser-chromium': true
  '@swc/core': true
  core-js: false
  esbuild: true
  playwright: true
  puppeteer: true

overrides:
  fast-uri: ^3.1.2
  qs: ^6.15.2
  webpack-dev-server: ^6.0.0

nodeLinker: hoisted
linkWorkspacePackages: true
preferWorkspacePackages: true
publicHoistPattern:
  - '*'

patchedDependencies:
  '@signalwire/docusaurus-plugin-llms-txt@1.2.2': patches/@signalwire__docusaurus-plugin-llms-txt@1.2.2.patch
