blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/apify/apify-sdk-js/discussions
    about: Got a question? Want to leave some feedback for the Crawlee team? Make a post in GitHub Discussions about it!
  - name: Discord
    url: https://discord.gg/jyEM2PRvMU
    about: Join our Discord server where you can talk with the Crawlee community, as well as the Apify team and get help if you have a question or are unsure of how to do something!
  - name: Apify SDK Documentation
    url: https://sdk.apify.com/
    about: Check out Apify SDK's documentation, maybe you'll find your solution there!

