name: Feature request
description: Request a new feature in Crawlee
labels: [feature]
body:
  - type: dropdown
    id: package
    attributes:
      label: Which package is the feature request for? If unsure which one to select, leave blank
      multiple: false
      options:
        - "@crawlee/core"
        - "@crawlee/cheerio (CheerioCrawler)"
        - "@crawlee/jsdom (JSDOMCrawler)"
        - "@crawlee/playwright (PlaywrightCrawler)"
        - "@crawlee/puppeteer (PuppeteerCrawler)"
        - "@crawlee/basic (BasicCrawler)"
        - "@crawlee/http (HttpCrawler)"
        - "@crawlee/browser (BrowserCrawler)"
        - "@crawlee/utils"
        - "@crawlee/browser-pool"
        - "@crawlee/memory-storage"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Feature
      description: A clear and concise description of what the problem is, or what feature you want to be implemented.
      placeholder: I'm always frustrated when..., I would love if there was a shortcut for..., A good addition would be...
    validations:
      required: true

  - type: textarea
    id: motive
    attributes:
      label: Motivation
      description: What made you want to suggest this feature? How would you use it in Crawlee and how will it help you?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Ideal solution or implementation, and any additional constraints
      description: What constraints would we need to ensure? How do you see this feature implemented or used by you?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions or implementations
      description: Have you considered any alternative solutions or features that would help you with this issue?

  - type: textarea
    id: additional-context
    attributes:
      label: Other context
      description: Any other context, screenshots, or file uploads that help us understand your feature request.
