module.exports = {
    docs: [
        {
            type: 'category',
            label: 'Guides',
            link: {
                type: 'generated-index',
                title: 'Guides',
                slug: '/guides',
                keywords: ['guides'],
            },
            items: [
                'guides/motivation',
                'guides/quick-start',
                'guides/apify-platform',
                'guides/getting-started',
                'guides/request-storage',
                'guides/result-storage',
                'guides/environment-variables',
                'guides/proxy-management',
                'guides/session-management',
                'guides/type-script-actor',
                'guides/docker-images',
            ],
        },
        {
            type: 'category',
            label: 'Examples',
            link: {
                type: 'generated-index',
                title: 'Examples',
                slug: '/examples',
                keywords: ['examples'],
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'examples',
                },
            ],
        },
        {
            label: 'Upgrading',
            type: 'link',
            href: 'https://crawlee.dev/docs/upgrading/upgrading-to-v3',
        },
    ],
};
