name: docs

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: Use Node.js 16
                uses: actions/setup-node@v2-beta
                with:
                    node-version: 16

            -   name: Set git identity
                run: |
                    git config --global user.name "Martin Adámek"
                    git config --global user.email "martin@apify.com"

            #    - name: Cache node_modules
            #      uses: actions/cache@v2
            #      with:
            #        path: '**/node_modules'
            #        key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/yarn.lock') }}

            -   name: Build & deploy docs
                run: |
                    # install project deps
                    npm ci --force
                    # go to website dir
                    cd website
                    # install website deps
                    npm ci --force
                    # build and deploy the docs
                    npm run deploy
                env:
                    GIT_USER: "B4nan:${{ secrets.GH_TOKEN }}"
                    GH_TOKEN: ${{ secrets.GH_TOKEN }}
