name: Build generic Actors

on:
    workflow_dispatch:
        inputs:
            web-scraper:
                description: apify/web-scraper
                type: boolean
                required: false
                default: true
            cheerio-scraper:
                description: apify/cheerio-scraper
                type: boolean
                required: false
                default: true
            playwright-scraper:
                description: apify/playwright-scraper
                type: boolean
                required: false
                default: true
            puppeteer-scraper:
                description: apify/puppeteer-scraper
                type: boolean
                required: false
                default: true
            jsdom-scraper:
                description: apify/jsdom-scraper
                type: boolean
                required: false
                default: true
            camoufox-scraper:
                description: apify/camoufox-scraper
                type: boolean
                required: false
                default: true
            version:
                description: Version to build
                type: string
                required: true
                default: '3.0'
            build-tag:
                description: Build tag
                type: string
                required: true
                default: version-3

jobs:
    push-to-apify:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                settings:
                    - actor: web-scraper
                      should-build: ${{ github.event.inputs.web-scraper }}
                    - actor: cheerio-scraper
                      should-build: ${{ github.event.inputs.cheerio-scraper }}
                    - actor: playwright-scraper
                      should-build: ${{ github.event.inputs.playwright-scraper }}
                    - actor: puppeteer-scraper
                      should-build: ${{ github.event.inputs.puppeteer-scraper }}
                    - actor: jsdom-scraper
                      should-build: ${{ github.event.inputs.jsdom-scraper }}
                    - actor: camoufox-scraper
                      should-build: ${{ github.event.inputs.camoufox-scraper }}
        steps:
            - uses: actions/checkout@v4

            - name: Build ${{ matrix.settings.actor }}
              uses: apify/push-actor-action@master
              if: matrix.settings.should-build == 'true'
              with:
                  token: ${{ secrets.APIFY_ACTOR_BUILD_TOKEN }}
                  build-tag: ${{ github.event.inputs.build-tag }}
                  version: ${{ github.event.inputs.version }}
                  working-directory: packages/actor-scraper/${{ matrix.settings.actor }}
